### ISSUE TITLE
func_matrix_simd.inl error

### ISSUE THREAD

**Issue by zleisure** [oppenfuture/hololux-demo#1]
func_matrix_simd.inl:67:27: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
[build]    glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));

**Comment by chubei-oppen** [comment]
glm/0.9.8.5@g-truc/stable doesn't build under gcc7.
